## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  
julia:
  - 1.4

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

git:
  depth: false

codecov: true